name: hello

database:  
 driverClass: org.postgresql.Driver  
 user: userpg  
 password: userpg
 url: jdbc:postgresql://localhost:5432/mytmdb
 
#metrics:

# reporters:
 
# - type: graphite
  
#   host: localhost
     
#   port: 2003
     
#   prefix: example
     
#   frequency: 10s
     